Insert into restaurant_table values (DEFAULT, 'Whataburger', 'dinner', 'https://www.gannett-cdn.com/presto/2020/06/23/PALE/ffec2959-faf9-47c1-a239-ef0f2740fb47-WHATBurger.jpg ')
Insert into restaurant_table values (DEFAULT, 'Olive Garden', 'dinner', 'https://www.tasteofhome.com/wp-content/uploads/2020/04/olive-garden-family-size-dinner-social.png')
Insert into restaurant_table values (DEFAULT, 'Razzoos', 'dinner', 'https://pbs.twimg.com/media/ERUJQLmWkAEQlYg.jpg')
Insert into restaurant_table values (DEFAULT, 'Waffle House', 'breakfast', 'https://www.wafflehouse.com/wp-content/themes/wahotheme/assets/menu_items/BREAKFAST_HEADER_2000x786.jpg')
Insert into restaurant_table values (DEFAULT, 'IHOP', 'breakfast', 'https://www.pymnts.com/wp-content/uploads/2018/04/ihop-qsr-technology.jpg')
Insert into restaurant_table values (DEFAULT, 'P.F. Changs', 'dinner', 'https://cdn.vox-cdn.com/thumbor/QYY6UwAMNmCUjVpGzL0jI0eFB9o=/0x0:1000x1000/1200x800/filters:focal(397x368:557x528)/cdn.vox-cdn.com/uploads/chorus_image/image/59182357/P.F._Chang_s.0.jpg')
Insert into restaurant_table values (DEFAULT, 'Pho', 'dinner', 'https://www.recipetineats.com/wp-content/uploads/2019/04/Beef-Pho_6.jpg')
Insert into restaurant_table values (DEFAULT, 'Taco Bell', 'dinner', 'https://www.tacobell.com/medias/blog-2019-new-menu-header.jpg?context=bWFzdGVyfGltYWdlc3wxNjYyNzd8aW1hZ2UvanBlZ3xpbWFnZXMvaDFhL2g5OC84OTI4NTEyMTE0NzE4LmpwZ3xjMjA5YzZjNTQyMmM0MWM1ZWE5N2Q1OGQ0NDJjYWVkMzdiNTE0MjMyMjRhMzhmMTZjNGEwYTc4YmMwOGYwOWYx')
Insert into restaurant_table values (DEFAULT, 'Dunkin Donuts', 'breakfast', 'https://4.bp.blogspot.com/-4w2aFa5c0eU/XG77JqInQGI/AAAAAAAAk2M/f22AFXZa56wFTTuQPmRvl91I8KxceTJugCLcBGAs/s1600/dunkindonuts.jpg')
Insert into restaurant_table values (DEFAULT, 'Starbucks', 'breakfast', 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/index-unhealthiest-starbucks-drinks-1572380007.jpg?crop=0.495xw:0.990xh;0,0&resize=640:*')
Insert into restaurant_table values (DEFAULT, 'KFC', 'dinner', 'https://www.joc.com/sites/default/files/field_feature_image/KFC_0.png')
Insert into restaurant_table values (DEFAULT, 'Sushi', 'dinner', 'https://rimage.gnst.jp/livejapan.com/public/article/detail/a/00/00/a0000370/img/basic/a0000370_main.jpg')
Insert into restaurant_table values (DEFAULT, 'Buffalo Wild Wings', 'dinner', 'https://moadrupalweb.blob.core.windows.net/moadrupalweb/processed/25288_2019-0147960%20Mall%20of%20America%20Social%201920x1080_1-small.jpg')
Insert into restaurant_table values (DEFAULT, 'In and Out', 'dinner', 'https://www.in-n-out.com/Frontend-Assembly/Telerik.Sitefinity.Frontend/content/images/homepage/double-double.png?package=INNOUT')
Insert into restaurant_table values (DEFAULT, 'Chuys', 'dinner', 'https://assets.simpleviewinc.com/simpleview/image/fetch/c_fill,h_830,q_75,w_1122/https://assets.simpleviewinc.com/simpleview/image/upload/crm/pwmva/chuy-s2-4eec556e5056a36_4eec564c-5056-a36a-07ee796fc488e07b.jpg')
Insert into restaurant_table values (DEFAULT, 'Cracker Barrel', 'breakfast', 'https://jtv.tv/wp-content/uploads/2020/03/crackerBarrel.jpg')
Insert into restaurant_table values (DEFAULT, 'Texas Roadhouse', 'dinner', 'https://assets.simpleviewinc.com/simpleview/image/fetch/c_fill,h_656,q_75,w_1024/https://assets.simpleviewinc.com/simpleview/image/upload/crm/york/texas-roadhouse-0ed327f05056a36_0ed32914-5056-a36a-07afc7e3a3aa7e6c.jpg')
Insert into restaurant_table values (DEFAULT, 'Chipotle', 'dinner', 'https://assets.macerichepicenter.com/FileManager/Property/Events/LakewoodCenter/Chipotle.jpg')
Insert into restaurant_table values (DEFAULT, 'Chick-fil-A', 'dinner', 'https://d1fd34dzzl09j.cloudfront.net/Images/CFACOM/Stories%20Images/2018/11/door%20dash/2web.jpg?h=960&w=1440&la=en')

Insert into food_table values (DEFAULT, 'Stroganoff', 'dinner', 'null', 'https://natashaskitchen.com/wp-content/uploads/2020/01/Ground-Beef-Stroganoff-3.jpg')
Insert into food_table values (DEFAULT, 'One Pan Pork Carnitas Tacos', 'dinner', 'https://www.hellofresh.com/recipes/one-pan-pork-carnita-tacos-5a2b08b9a2882a5fa04ae892', 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_500,q_auto,w_1900/hellofresh_s3/image/one-pan-pork-carnita-tacos-337e7f15.jpg')
Insert into food_table values (DEFAULT, 'Chicken Fried Rice', 'dinner', 'null', 'https://www.averiecooks.com/wp-content/uploads/2016/02/chickenfriedrice-10.jpg')
Insert into food_table values (DEFAULT, 'Pancakes', 'breakfast', 'null', 'https://media.eggs.ca/assets/RecipePhotos/_resampled/FillWyIxMjgwIiwiNzIwIl0/Fluffy-Pancakes-New-CMS.jpg')
Insert into food_table values (DEFAULT, 'Spaghetti Bolognese', 'dinner', 'https://www.southyourmouth.com/2015/01/bolognese-sauce.html', 'https://sugarspiceslife.com/wp-content/uploads/2019/03/Greek-Meat-Sauce-with-Spaghetti-500x375.jpg')
Insert into food_table values (DEFAULT, 'Pigs in the Blanket', 'breakfast', 'null', 'https://mobile-cuisine.com/wp-content/uploads/2013/04/pigs-in-a-blanket-fun-facts.jpg')
Insert into food_table values (DEFAULT, 'French Toast', 'breakfast', 'null', 'https://www.momables.com/wp-content/uploads/2013/12/Egg-free-french-toast_post.jpg')
Insert into food_table values (DEFAULT, 'Chicken Enchiladas', 'dinner', 'https://www.hellofresh.com/recipes/salsa-verde-chicken-enchiladas-5dfd0bae39b70a23332c4678', 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_auto,w_2600/hellofresh_s3/image/5dfd0bae39b70a23332c4678-f7ebbc67.jpg')
Insert into food_table values (DEFAULT, 'Sweet and Sour Chicken', 'dinner', 'https://www.hellofresh.com/recipes/sweet-and-sour-chicken-5b03394a30006c19316d2f92', 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_auto,w_2600/hellofresh_s3/image/sweet-and-sour-chicken-5f547a93.jpg')
Insert into food_table values (DEFAULT, 'Chicken Parmesan', 'dinner', 'https://www.hellofresh.com/recipes/sweet-and-sour-chicken-5b03394a30006c19316d2f92', 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_auto,w_2600/hellofresh_s3/image/sweet-and-sour-chicken-5f547a93.jpg')
Insert into food_table values (DEFAULT, 'Stir-fry', 'dinner', 'null', 'https://d1e3z2jco40k3v.cloudfront.net/-/media/mccormick-us/recipes/mccormick/b/800/beef_stir_fry_and_vegetable_800x800.jpg?rev=c24f27c417c6426eb454d1645a2de64e&vd=20200628T062145Z&hash=426B27FC0316D65A43AC3E508A473A7F')
Insert into food_table values (DEFAULT, 'Meatloaf', 'dinner', 'null', 'https://www.jessicagavin.com/wp-content/uploads/2018/11/meatloaf-6-1200.jpg')
Insert into food_table values (DEFAULT, 'Pad Thai', 'dinner', 'https://lifemadesimplebakes.com/homemade-pad-thai/', 'https://i2.wp.com/lifemadesimplebakes.com/wp-content/uploads/2019/09/pad-thai-resize-4.jpg')
Insert into food_table values (DEFAULT, 'Chili', 'dinner', 'null', 'https://images-gmi-pmc.edge-generalmills.com/c19575ed-c744-4c56-bf83-59d429b0fa49.jpg')
Insert into food_table values (DEFAULT, 'BBQ Burnt Ends', 'dinner', 'null', 'https://pbs.twimg.com/media/DeeNIn5XkAAb-3f.jpg')
Insert into food_table values (DEFAULT, 'Breakfast Sandwich', 'breakfast', 'null', 'https://www.eatatjacks.com/wp-content/uploads/2020/05/big-breakfast-sandwich.jpg')
Insert into food_table values (DEFAULT, 'Chicken Pot Pie', 'dinner', 'https://www.twopeasandtheirpod.com/chicken-pot-pie/', 'https://www.twopeasandtheirpod.com/wp-content/uploads/2016/11/Chicken-Pot-Pie-4.jpg')
Insert into food_table values (DEFAULT, 'Tikka Masala', 'dinner', 'null', 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2010/4/28/0/EA1316_lamb-tikka-masala_s4x3.jpg.rend.hgtvcom.826.620.suffix/1371591065047.jpeg')
